__version__ = "0.1.0"
__description__ = "fetch, munge, and parse résumés and job postings"
__url__ = "https://github.com/datakind/msvdd_Bloc"
__maintainer__ = "Burton DeWilde"
__maintainer_email__ = "burtdewilde@gmail.com"
